### ISSUE TITLE
How to debug 'SassC::SyntaxError: Unknown error occurred'

### ISSUE THREAD

**Issue by pkmiec** [bolandrm/sassc-rails#20]
I'm trying to speed up asset compilation with SassC. I'm getting a generic error. Any idea on how to debug this?

ruby 2.1.5
sassc 1.2.0
sassc-rails 0.1.0

**Comment by bolandrm** [comment]
This is a probably a syntax error that Libsass doesn't do a good job of explaining.

Are you able to narrow this down at all?  If your CSS is split into multiple files, can you incrementally add files until you figure out which part of the CSS is at fault?

If you can narrow it down to the particular CSS that is causing the problem, we can create a issue for Libsass.

**Comment by pkmiec** [comment]
Yes, I can attempt to do so. I will report what I find out.

**Comment by pkmiec** [comment]
I had this pattern,
```sass
$grid-classes: ();

@mixin generate($viewport) {
  $grid-classes: append($grid-classes, ..., comma);
  ...
}

@include generate(small);
@include generate(medium);
@include generate(large);

#{$grid-classes} {
 ...
}
```

which worked in sass / sass-rails. 

The problem in sassc is that the global `$grid-classes` variable is not modified by the mixin. So `#{$grid-classes}` at the end is empty, which causes the `Unknown error occurred` error.

I'm not sure whether sass or sassc has the correct treatment of global variables inside of mixins. But I changed my code so that it works with both sass and sassc.

**Comment by bolandrm** [comment]
Thanks for the follow up.  I'm going to close this - since it's a libsass issue.  I'd encourage you to report this behavior over at https://github.com/sass/libsass/issues.
