### ISSUE TITLE
wildcard/globbed imports are not implemented yet

### ISSUE THREAD

**Issue by ff-rboutotte** [bolandrm/sassc-rails#3]
Prior to integration I had this in my code working fine:
```
@import 'common/*';
```
I had to convert any css imports that used wildcards to import a whole path to import each stylesheet separately. Reading up the old convention may not be supported going forward but wasn't clear to me, so just wanted to confirm/log on potential issue here. Feel free to close out if this this is no longer supported using sassc. Thanks

**Comment by bolandrm** [comment]
Hey!  This gem is still very much a work in progress.   We have not implemented wildcard (globbed) imports yet.  I'll leave this open as a reminder.

**Comment by ff-rboutotte** [comment]
Thanks, yes I understand this is very new and work in progress, but very interested in this gem.

**Comment by bolandrm** [comment]
@ff-rboutotte I've implemented globbed imports in version `0.0.7` - please give it a try!
