### ISSUE TITLE
Sprockets::SassFunctions end up returning Ruby Sass to SassC (bad)

### ISSUE THREAD

**Issue by edward** [bolandrm/sassc-rails#30]
If a custom Sass function that wraps an existing `Sprockets::SassFunctions` method calls `super`, it ends up returning a `Sass` type, which has no `#to_native` method defined on it, then makes SassC blow up.

This is kinda awkward to test since the code that depends on the `#to_native` is in [`sassc-ruby/functions_helper.rb`](https://github.com/bolandrm/sassc-ruby/blob/master/lib/sassc/functions_handler.rb#L54) but the code that introduces Sass functions that return a Ruby Sass type is in [`sassc-rails/rails/functions.rb`](https://github.com/bolandrm/sassc-rails/blob/master/lib/sassc/rails/functions.rb#L11)

I’m going to test this in sassc-rails for now and prepare a PR, but I’m open to feedback.

**Comment by edward** [comment]
@bolandrm (This also means that https://github.com/bolandrm/sassc-ruby/commit/9bde3184c3a1c9ccc22c608aba4e9990349e5193 will break `sassc-rails` so please let me get in a fix before we release a new version.)

**Comment by edward** [comment]
@bolandrm Okay, I’ve got the PRs in https://github.com/bolandrm/sassc-ruby/pull/16 and https://github.com/bolandrm/sassc-rails/pull/31

I’m not a fan of monkeypatching Ruby Sass types like this, but I think it’s a small enough and obvious enough alteration that it’s the best way forward, given our options.

We get test coverage for this change through existing tests in sassc-rails that check that the asset url methods and such work.

I also investigated an approach to fixing this purely on the sassc-ruby side that did something like a `value.extend(SassC::Script::NativeColor)` on the return values of Sprockets’ Sass functions, but I felt like it made more sense to have the code live in sassc-rails, since it’s where this issue is caused.

**Comment by bolandrm** [comment]
Handling on SassC-Ruby end
