### ISSUE TITLE
Comment block causes invalid top-lvel expression error

### ISSUE THREAD

**Issue by ff-rboutotte** [bolandrm/sassc-rails#5]
I get this error:
```
ActionView::Template::Error (Error: invalid top-level expression
        on line 208 of app/assets/stylesheets/_main.scss
):
```
This only happens in these two cases (Not sure if this was valid CSS/SCSS syntax before, but now is flagged):
```
.my_css_class /* Some comment */ {
}
.my_other_class { /* Some comment */
}
```

**Comment by bolandrm** [comment]
Hey, thanks for the report, but I'm going to close this.  I believe it's an issue with libsass (https://github.com/sass/libsass), not this library.  I'd encourage you to open an issue over at that repo.
