### ISSUE TITLE
Fails to compile with non-UTF8 characters

### ISSUE THREAD

**Issue by constantm** [bolandrm/sassc-rails#7]
Looks like it works perfectly in development but when running tests it doesn't compile:

```
Error compiling CSS asset
Sass::SyntaxError: Undefined variable: "$light-gray"
   (sass):268
```

The variable does indeed exist in a file called `vars.scss`, and works perfectly in development. I'm not clever enough to figure this out myself, but please let me know what else I can do to help sort this out. :)

EDIT: I figured out this was being caused by non-UTF8 characters such as a copyright sign in my scss files.

**Comment by bolandrm** [comment]
Hello, is it possible for you to provide a simplified example of this issue?  I'm wondering if it's an issue with libsass itself.

**Comment by constantm** [comment]
Simply adding something like a © in one of the files should reproduce this.

**Comment by bolandrm** [comment]
Fixed!  https://github.com/bolandrm/sassc-ruby/pull/2   / https://github.com/bolandrm/sassc-ruby/pull/3
