### ISSUE TITLE
"random" segmentation faults

### ISSUE THREAD

**Issue by constantm** [bolandrm/sassc-rails#8]
Running `rake assets:precompile` causes a segmentation fault.

Stack trace here: https://gist.github.com/constantm/b2b09a55d96fa2f1cce2

**Comment by frankh** [comment]
I also get a seg fault

Stack trace: https://gist.github.com/frankh/423c97183ceae41a526b

**Comment by arjun810** [comment]
Having similar segfaults on Ubuntu. Works really well other than that..

**Comment by arjun810** [comment]
Also, my segfaults aren't necessarily with precompile -- they're just random. I'll change a .sass file, reload the page, and it'll work. I'll change the same thing again, and it'll segfault.

**Comment by bolandrm** [comment]
This is occurring for me as well.  This is very much a work in progress still.  I'm going to work on debugging it.

**Comment by bolandrm** [comment]
I think I've corrected this issue - can you guys try updating to version 0.0.5?

**Comment by frankh** [comment]
Seems to have fixed it for me (hard to know for sure because it didn't segfault every time)

Thanks!
