### ISSUE TITLE
Remove sprockets version dependency (setup testing against multiple versions of Rails and Sprockets)

### ISSUE THREAD

**Issue by jlaw90** [bolandrm/sassc-rails#9]
Currently this gem has a requirement for sprockets being version 3.0.0.beta.6, can this be generalised?

**Comment by bolandrm** [comment]
Absolutely.  I intend to set up testing against multiple gemfiles for multiple versions of Rails and Sprockets.

Currently I need to resolve issue https://github.com/bolandrm/sassc-rails/issues/8 before proceeding with anything else.

**Comment by bolandrm** [comment]
@jlaw90 I've set up testing across multiple versions of Rails and Sprockets.  It should now support:

```
  spec.add_dependency 'rails', '>= 4.0.0'
  spec.add_dependency 'sprockets', '> 2.11'
```

Does this help?

**Comment by jlaw90** [comment]
@bolandrm that should do it, thanks!
